version: "3.9"

networks:
  #owntracks_network:
  #  name: owntracks_network
  reverse-proxy:
    external: true

services:
  siyuan:
    image: b3log/siyuan:v3.1.10
    networks:
      reverse-proxy:
    command: ['--workspace=/siyuan/workspace/', '--accessAuthCode=password']
    ports:
      - 6806:6806
    volumes:
      - /mnt/user/docker/volumes/siyuan/workspace:/siyuan/workspace
    #restart: unless-stopped
    environment:
      # A list of time zone identifiers can be found at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=America/Chicago
      - PUID=99 
      - PGID=100
    deploy:
      labels:
        - "traefik.enable=true"
        #- "traefik.http.routers.newapp-auth.rule=Host(`notes.actuary.dev`)"
        #- "traefik.http.routers.newapp.entrypoints=websecure"
        #- "traefik.http.routers.newapp.tls=true"
        #- "traefik.http.routers.newapp.tls.certresolver=myresolver"
        - "traefik.http.routers.notes.rule=Host(`notes.actuary.dev`)"
        - "traefik.http.routers.notes.entrypoints=websecure"
        - "traefik.http.routers.notes.service=notes"
        - "traefik.http.routers.notes.tls.certresolver=myresolver"
        - "traefik.http.services.notes.loadbalancer.server.port=6806"
        #- "traefik.http.middlewares.newapp-auth.forwardauth.address=https://authentik.actuary.dev/outpost.goauthentik.io/"
        #- "traefik.http.middlewares.newapp-auth.forwardauth.trustForwardHeader=true"
        #- "traefik.http.routers.newapp.middlewares=newapp-auth"
        ## Middlewares
        - "traefik.http.routers.notes.middlewares=authentik"
        #DIUN
        - diun.enable = true
        - diun.notify_on = new
