version: "3.9"

networks:
  reverse-proxy:
    external: true

services:
  main:
    image: b3log/siyuan:v3.1.20 #https://hub.docker.com/r/b3log/siyuan/tags
    networks:
      reverse-proxy:
    command: ['--workspace=/siyuan/workspace/']
    ports:
      - 6806:6806
    volumes:
      - /mnt/user/docker/volumes/siyuan/workspace:/siyuan/workspace
    #restart: unless-stopped
    environment:
      # A list of time zone identifiers can be found at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=America/Chicago
      - PUID=99 
      - PGID=100
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.notes.rule=Host(`notes.actuary.dev`)"
        - "traefik.http.routers.notes.entrypoints=websecure"
        - "traefik.http.routers.notes.service=notes"
        - "traefik.http.routers.notes.tls.certresolver=myresolver"
        - "traefik.http.services.notes.loadbalancer.server.port=6806"
        ## Middlewares
        - "traefik.http.routers.notes.middlewares=authentik"
        #DIUN
        - diun.enable = true
        - diun.notify_on = new
