name: 'Deploy'
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  checkout-repository:
    runs-on: [coral]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'Actuary-LLC/siyuan'
          ref: 'main'       
      #- name: Configure application
      #  run: |
      #    sed -i 's/${AUTHENTIK_ID_OWNTRACKS}/${{ vars.AUTHENTIK_ID_OWNTRACKS }}/' config.yaml
      #    sed -i 's/${AUTHENTIK_SECRET_OWNTRACKS}/${{ secrets.AUTHENTIK_SECRET_OWNTRACKS }}/' config.yaml
      #    cat config.yaml
      #- name: Sleep for 150 seconds
      #  run: sleep 150s
      #  shell: bash
  deploy-task:
    needs: checkout-repository
    runs-on: [coral]
    env:
      TAG: ${{ github.sha }}
    steps:
      - name: Remove and redeploy services
        run: |
          SERVICES=("b3log_siyuan") 
          for SERVICE_NAME in "${SERVICES[@]}"; do
            if docker service ls | grep -q $SERVICE_NAME; then
              docker service rm $SERVICE_NAME;
              echo "Service $SERVICE_NAME removed."
            else echo "Service $SERVICE_NAME is not running."
            fi
          done
      - run: | 
          docker stack deploy -c siyuan.yaml b3log
